Repository AY1920S1-CS2113T-W12-2/main, pull requests merged in 2019-10, with the labels that each got.

#74 Add CheckFutureBalanceCommand and InternalTransferCommand for D-Bank
  Command_List/MoneyCommandList
  data/iconPath.txt
  data/moneyAccount.txt
  src/main/java/MainWindow.java
  src/main/java/controlpanel/Parser.java
  src/main/java/money/Account.java
  src/main/java/money/BankTracker.java
  src/main/java/moneycommands/CheckFutureBalanceCommand.java
  src/main/java/moneycommands/CreateBankAccountCommand.java
  src/main/java/moneycommands/InternalTransferCommand.java
  src/main/java/moneycommands/ListBankTrackerCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#75 Implement the command to check current income and expenditure histogram
  Command_List/MoneyCommandList
  src/main/java/DialogBox.java
  src/main/java/Duke.java
  src/main/java/Histogram.java
  src/main/java/MainWindow.java
  src/main/java/controlpanel/Parser.java
  src/main/java/moneycommands/GraphCommand.java
  src/main/resources/view/Histogram.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#105 Fix Bug for help Package
  src/main/java/MainWindow.java
  src/main/java/help/AutoComplete.java
  src/main/resources/view/MainWindow.fxml
Labels: severity.High

#116 add testInstalment
  data/account-test.txt
  data/moneyAccountTemp177410154806310280.txt
  data/moneyAccountTemp8095341480167884096.txt
  src/main/java/money/Instalment.java
  src/main/java/moneycommands/DeleteInstalmentCommand.java
  src/test/java/InstalmentTest.java
Labels: priority.High

#117 Checkstyle help package, Instalment and its relevant, Mainwindow
  src/main/java/MainWindow.java
  src/main/java/controlpanel/MoneyStorage.java
  src/main/java/help/AutoComplete.java
  src/main/java/help/History.java
  src/main/java/money/Account.java
  src/main/java/money/Instalment.java
  src/main/java/moneycommands/AddInstalmentCommand.java
  src/main/java/moneycommands/AutoUpdateInstalmentCommand.java
  src/main/java/moneycommands/DeleteInstalmentCommand.java
  src/main/java/moneycommands/ListInstalmentCommand.java
Labels: priority.High
